name: Run CIACAM

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 3 * * 1-5'   # 09:15 AM IST
    - cron: '45 4 * * 1-5'   # 10:15 AM IST
    - cron: '45 5 * * 1-5'   # 11:15 AM IST
    - cron: '41 6 * * 1-5'   # 12:15 PM IST
    - cron: '45 7 * * 1-5'   # 01:15 PM IST
    - cron: '45 8 * * 1-5'   # 02:15 PM IST
    - cron: '41 9 * * 1-5'   # 03:15 PM IST
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Remove conflicting logging package
        run: |
          pip uninstall -y logging || true

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --force-reinstall setuptools wheel

      - name: Load environment variables
        run: |
          echo "client_id=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "APP_TYPE=${{ secrets.APP_TYPE }}" >> $GITHUB_ENV
          echo "secret_key=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "fyers_id=${{ secrets.FYERS_ID }}" >> $GITHUB_ENV
          echo "TOTP_KEY=${{ secrets.TOTP_KEY }}" >> $GITHUB_ENV
          echo "pin=${{ secrets.PIN }}" >> $GITHUB_ENV
          echo "redirect_uri=${{ secrets.REDIRECT_URI }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Debug TOTP Key
        run: |
           echo "TOTP_KEY length: ${#TOTP_KEY}"  # Check if the length is correct
           echo "TOTP_KEY (masked): ${TOTP_KEY:0:4}******"  # Print first few characters

      - name: Debug environment variables
        run: env | grep -E 'client_id|APP_TYPE|secret_key|fyers_id|TOTP_KEY|pin|redirect_uri'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pyotp  # Ensure pyotp is installed

      - name: Debug installed packages
        run: pip list

      - name: Run login script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python cia_cam.py


      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add and commit files
        run: |
          git add -A
          git commit -m "Auto-commit CSV, TXT, JSON, and log files" || true
          git push origin main || true
